server:
  port: 8081
  session:
    timeout: 1800
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.jeff.yue.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
